[package]
name = "mosaic_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Yew
yew = { version = "0.20", features = ["csr"] }

# WASM
wasm-bindgen-futures = "0.4"
